#!/usr/bin/env python3
"""build_employer_pages.py — static /employers/{slug} pages for the biggest PERM sponsors.

SEO plan item 3 (2026-09-24). Generates, from data only:

  employers/<slug>.html   one static, JS-free profile per registry employer
  employers.html          the /employers hub (top-N by PERM volume + A–Z)
  sitemap.xml             the block between <!--il-ssr:employers--> markers
  employer.html           the block between <!--il-ssr:static-employers--> markers
                          (slug map so the JS profile can link to its static page)

Data sources (every number on a page comes from one of these):
  data/employer_index.json        ranking universe: DOL OFLC PERM + LCA disclosure
                                  store, FY2008–FY2026 (the leaderboard's `perm`)
  worker  /api/employers/<slug>/h1b   per-employer PERM by FY, LCA by FY, SOC wages,
                                      PERM job titles, salary trend (same store)
  worker  /api/employers/<slug>       live case-status tracker (filings since Nov 2024)
  worker  /api/meta                   live tracker timestamp
  data/dashboard_data.json        DOL processing frontier + average days (site-wide)
  data/employers_top300_extras.json   optional: worksite locations + filing→decision
                                  days per employer from the raw PERM disclosure
                                  files (built offline by build_employer_extras.py)

Registry / snapshot: data/employers_top300.json. It pins each employer's slug (so a
URL never changes when a display name is re-spelled), stores the last fetched
payloads (so the pages still build when the worker is unreachable) and a
per-employer content fingerprint + lastmod (so sitemap lastmod only moves when
the page's numbers actually changed since the committed snapshot).

Modes:
  --select        (re)compute the top-N membership from data/employer_index.json
                  and add new members to the registry (never removes any)
  --refresh       fetch fresh worker data for every registry member (falls back
                  to the stored payload per employer on any error)
  --render        write the pages / hub / sitemap block / employer.html block
  --check         report only, write nothing
  --top N         membership size for --select (default 300)

Deploy time: render_live.py calls deploy_step() = --refresh --render, non-fatal.
Python 3.9+ (stdlib only).
"""
from __future__ import annotations

import argparse
import concurrent.futures as cf
import datetime as dt
import hashlib
import html as html_mod
import json
import os
import re
import sys
import unicodedata
import urllib.error
import urllib.request
from typing import Any, Dict, List, Optional, Tuple

try:
    from zoneinfo import ZoneInfo
    ET = ZoneInfo("America/New_York")
except Exception:  # pragma: no cover
    ET = dt.timezone(dt.timedelta(hours=-4))

SITE = "https://immilane.com"
API_BASE = os.environ.get("IMMILANE_EMPLOYER_API", "https://immilane-api.younusahamad.workers.dev").rstrip("/")
UA = "ImmiLane-render/1.0 (+https://immilane.com)"
REGISTRY_REL = "data/employers_top300.json"
EXTRAS_REL = "data/employers_top300_extras.json"
INDEX_REL = "data/employer_index.json"
DASH_REL = "data/dashboard_data.json"
OUT_DIR = "employers"
HUB_REL = "employers.html"
DEFAULT_TOP = 300
FETCH_TIMEOUT = 25
FETCH_WORKERS = 8
GENERATED_BANNER = "<!-- GENERATED by scripts/build_employer_pages.py — do not edit by hand; edit the script and re-run. -->"


# ── helpers ─────────────────────────────────────────────────────────────────
def normalize_slug(s: str) -> str:
    """Same rule as employer.html employerSlug() / worker normalizeSlug()."""
    if not s:
        return ""
    s = unicodedata.normalize("NFKD", str(s))
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = s.lower().replace("&", " and ")
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s[:200]


def esc(s: Any) -> str:
    return html_mod.escape("" if s is None else str(s), quote=True)


def n(v: Any) -> str:
    if v is None:
        return "—"
    try:
        if isinstance(v, float) and not v.is_integer():
            return f"{v:,.1f}"
        return f"{int(round(v)):,}"
    except (TypeError, ValueError):
        return "—"


def usd(v: Any) -> str:
    if v is None:
        return "—"
    try:
        return "$" + f"{int(round(float(v))):,}"
    except (TypeError, ValueError):
        return "—"


def pct(num: float, den: float, digits: int = 1) -> Optional[float]:
    if not den:
        return None
    return round(num / den * 100, digits)


def fmt_pct(p: Optional[float], digits: int = 1) -> str:
    return "—" if p is None else (f"{p:.{digits}f}%" if digits else f"{int(round(p))}%")


def parse_iso(s: str) -> dt.datetime:
    s = s.strip()
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    d = dt.datetime.fromisoformat(s)
    if d.tzinfo is None:
        d = d.replace(tzinfo=dt.timezone.utc)
    return d


def fmt_et_long(iso: str) -> str:
    d = parse_iso(iso).astimezone(ET)
    return d.strftime("%b %-d, %Y, %-I:%M %p") + " ET"


def fmt_date(iso: str) -> str:
    """'2026-09-16' -> 'Sep 16, 2026'."""
    try:
        d = dt.date.fromisoformat(iso[:10])
        return d.strftime("%b %-d, %Y")
    except Exception:
        return iso or "—"


def fmt_month(iso: str) -> str:
    try:
        d = dt.date.fromisoformat(iso[:10])
        return d.strftime("%B %Y")
    except Exception:
        return iso or "—"


def fy_short(fy: str) -> str:
    return fy.replace("FY", "FY ") if fy else "—"


def today_et() -> dt.date:
    return dt.datetime.now(ET).date()


def now_et_str() -> str:
    return dt.datetime.now(ET).strftime("%b %-d, %Y, %-I:%M %p") + " ET"


def sub_marked(text: str, name: str, inner: str) -> str:
    pat = rf"(<!--il-ssr:{re.escape(name)}-->).*?(<!--/il-ssr:{re.escape(name)}-->)"
    new, cnt = re.subn(pat, lambda m: m.group(1) + inner + m.group(2), text, count=1, flags=re.S)
    if cnt != 1:
        raise RuntimeError(f"marker not found: {name}")
    return new


# ── worker fetch ─────────────────────────────────────────────────────────────
def http_json(url: str, timeout: int = FETCH_TIMEOUT) -> Tuple[int, Any]:
    req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status, json.loads(r.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        try:
            body = json.loads(e.read().decode("utf-8"))
        except Exception:
            body = None
        return e.code, body


def fetch_with_retry(url: str, tries: int = 3) -> Tuple[int, Any]:
    last: Tuple[int, Any] = (0, None)
    for i in range(tries):
        try:
            last = http_json(url)
        except Exception as e:  # network / timeout
            last = (0, {"error": str(e)})
        if last[0] in (200, 404):
            return last
    return last


def trim_h1b(h: dict) -> dict:
    """Keep only what the pages render (keeps the registry small and stable)."""
    def yr(y, keys):
        return {k: y.get(k) for k in keys if k in y}
    out = {
        "slug": h.get("slug"), "name": h.get("name"), "fy": h.get("fy"),
        "total": h.get("total"), "wage_median_all": h.get("wage_median_all"),
        "aliasNames": [a for a in (h.get("aliasNames") or []) if a][:8],
        "memberSlugs": list(h.get("memberSlugs") or []),
        "partialFYs": list(h.get("partialFYs") or []),
        "permByYear": [yr(y, ("fy", "cert", "denied", "withdrawn", "salary_median", "partial")) for y in (h.get("permByYear") or [])],
        "lcaByYear": [yr(y, ("fy", "cert", "denied", "withdrawn", "total", "wage_median", "pw_median", "partial")) for y in (h.get("lcaByYear") or [])],
        "socs": [yr(s, ("soc", "title", "n", "wage_median", "wage_p10", "wage_p90", "pw_median")) for s in sorted(h.get("socs") or [], key=lambda s: -(s.get("n") or 0))[:10]],
        "permTitlesAll": [yr(t, ("title", "n")) for t in (h.get("permTitlesAll") or [])[:10]],
        "salaryTrend": [yr(y, ("fy", "h1b_offered", "prevailing", "gc", "partial")) for y in (h.get("salaryTrend") or [])],
    }
    return out


def trim_live(l: dict) -> dict:
    return {
        "name": l.get("name"), "total": l.get("total"), "statuses": dict(l.get("statuses") or {}),
        "certified": l.get("certified"), "denied": l.get("denied"),
        "firstFiling": l.get("firstFiling"), "lastFiling": l.get("lastFiling"),
        "topTitles": [{"title": t.get("title"), "count": t.get("count")} for t in (l.get("topTitles") or [])[:10]],
    }


def fetch_employer(entry: dict, probe_all: bool) -> dict:
    """Fetch h1b + live payloads for one registry entry. Returns a dict of updates
    (never raises; on failure the caller keeps the stored payloads)."""
    upd: Dict[str, Any] = {"fetchErrors": []}
    name_slug = normalize_slug(entry["name"])
    st, h = fetch_with_retry(f"{API_BASE}/api/employers/{name_slug}/h1b")
    if st == 200 and isinstance(h, dict) and "permByYear" in h:
        upd["h1b"] = trim_h1b(h)
        upd["h1bSlug"] = h.get("slug") or name_slug
    else:
        upd["fetchErrors"].append(f"h1b {st}")
    h1b = upd.get("h1b") or entry.get("h1b") or {}
    # Live tracker: keyed by the scanner's own name slugs. Probe the canonical,
    # the name slug and every member slug once; afterwards only the slug that hit.
    if probe_all or not entry.get("liveSlugs"):
        cands: List[str] = []
        for c in [name_slug, h1b.get("slug"), entry.get("a")] + list(h1b.get("memberSlugs") or []):
            c = normalize_slug(c or "")
            if c and c not in cands:
                cands.append(c)
    else:
        cands = list(entry["liveSlugs"])
    hits: List[Tuple[str, dict]] = []
    for c in cands:
        st, l = fetch_with_retry(f"{API_BASE}/api/employers/{c}")
        if st == 200 and isinstance(l, dict) and "statuses" in l:
            hits.append((c, l))
        elif st != 404:
            upd["fetchErrors"].append(f"live {c} {st}")
    if hits:
        # The scanner keys cases by the exact employer_name string, so reunified
        # name variants are disjoint case sets: merge them (sum statuses, union
        # titles, min/max filing dates) the same way the store merges permByYear.
        hits.sort(key=lambda h: -(h[1].get("total") or 0))
        merged = trim_live(hits[0][1])
        merged["variants"] = [{"slug": c, "name": l.get("name"), "total": l.get("total")} for c, l in hits]
        if len(hits) > 1:
            statuses: Dict[str, int] = {}
            titles: Dict[str, int] = {}
            firsts, lasts = [], []
            for _, l in hits:
                for k, v in (l.get("statuses") or {}).items():
                    statuses[k] = statuses.get(k, 0) + (v or 0)
                for t in l.get("topTitles") or []:
                    if t.get("title"):
                        titles[t["title"].strip()] = titles.get(t["title"].strip(), 0) + (t.get("count") or 0)
                if l.get("firstFiling"):
                    firsts.append(l["firstFiling"])
                if l.get("lastFiling"):
                    lasts.append(l["lastFiling"])
            merged.update({
                "total": sum((l.get("total") or 0) for _, l in hits), "statuses": statuses,
                "certified": statuses.get("CERTIFIED", 0), "denied": statuses.get("DENIED", 0),
                "firstFiling": min(firsts) if firsts else "", "lastFiling": max(lasts) if lasts else "",
                "topTitles": [{"title": t, "count": c} for t, c in sorted(titles.items(), key=lambda kv: -kv[1])[:10]],
            })
        upd["liveSlug"] = hits[0][0]
        upd["liveSlugs"] = [c for c, _ in hits]
        upd["live"] = merged
        upd["liveHits"] = len(hits)
    elif not upd["fetchErrors"]:
        upd["live"] = None  # genuinely no live entry (all 404)
        upd["liveSlug"] = None
        upd["liveSlugs"] = []
    return upd


# ── registry ────────────────────────────────────────────────────────────────
def load_json(path: str, default=None):
    if not os.path.exists(path):
        return default
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def save_json(path: str, obj) -> None:
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(obj, f, separators=(",", ":"), ensure_ascii=False)
    os.replace(tmp, path)


def select_members(root: str, reg: dict, top: int) -> Tuple[dict, List[str]]:
    """Top-N by PERM volume from the index; ties broken by total filings, then name.
    Existing members keep their slug; new members get a collision-free slug."""
    idx = load_json(os.path.join(root, INDEX_REL))
    emps = idx["employers"]
    ranked = sorted(emps, key=lambda e: (-(e.get("perm") or 0), -(e.get("total") or 0), (e.get("n") or "").lower()))
    members = reg.setdefault("employers", [])
    by_name = {m["name"]: m for m in members}
    used = {m["slug"] for m in members}
    added: List[str] = []
    for rank, e in enumerate(ranked[:top], 1):
        name = e["n"]
        if name in by_name:
            continue
        slug = normalize_slug(name)
        base, k = slug, 2
        while slug in used:
            slug = f"{base}-{k}"
            k += 1
        used.add(slug)
        m = {"slug": slug, "name": name, "a": e.get("a"), "addedAt": today_et().isoformat(), "addedRank": rank}
        members.append(m)
        by_name[name] = m
        added.append(slug)
    reg["selection"] = {"top": top, "rule": "employer_index.json `perm` desc (DOL OFLC PERM disclosure FY2008–FY2026, cert+denied+withdrawn), ties: total filings desc, then name",
                        "selectedAt": dt.datetime.now(ET).isoformat(timespec="seconds"), "indexGeneratedAt": idx.get("generatedAt")}
    return reg, added


def apply_index(root: str, reg: dict) -> None:
    """Rank/perm/lca/total for every member from the committed index (cheap)."""
    idx = load_json(os.path.join(root, INDEX_REL))
    emps = idx["employers"]
    ranked = sorted(emps, key=lambda e: (-(e.get("perm") or 0), -(e.get("total") or 0), (e.get("n") or "").lower()))
    pos = {e["n"]: (i + 1, e) for i, e in enumerate(ranked)}
    reg["index"] = {"generatedAt": idx.get("generatedAt"), "totalEmployers": idx.get("totalEmployers"),
                    "totalPerm": idx.get("totalPerm"), "totalLca": idx.get("totalLca"), "universe": idx.get("universe")}
    for m in reg["employers"]:
        p = pos.get(m["name"])
        if p:
            m["rank"], e = p[0], p[1]
            m["perm"], m["lca"], m["total"] = e.get("perm") or 0, e.get("lca") or 0, e.get("total") or 0
        # else: keep the last known numbers (name dropped from the index)


def refresh(reg: dict, probe_all: bool = False) -> dict:
    members = reg["employers"]
    with cf.ThreadPoolExecutor(max_workers=FETCH_WORKERS) as ex:
        results = list(ex.map(lambda m: fetch_employer(m, probe_all), members))
    ok = 0
    for m, upd in zip(members, results):
        errs = upd.pop("fetchErrors", [])
        if "h1b" in upd:
            ok += 1
        for k, v in upd.items():
            m[k] = v
        m["fetchErrors"] = errs
    st, meta = fetch_with_retry(f"{API_BASE}/api/meta")
    if st == 200 and isinstance(meta, dict):
        reg["liveMeta"] = meta
    reg["refreshedAt"] = dt.datetime.now(ET).isoformat(timespec="seconds")
    reg["refreshStats"] = {"members": len(members), "h1bOk": ok, "errors": sum(1 for m in members if m.get("fetchErrors"))}
    return reg


# ── derived numbers ─────────────────────────────────────────────────────────
def perm_stats(h1b: dict) -> dict:
    """Port of employer.html permStatsFromDisclosure()."""
    cert = den = wd = 0
    fys = []
    for y in h1b.get("permByYear") or []:
        cert += y.get("cert") or 0
        den += y.get("denied") or 0
        wd += y.get("withdrawn") or 0
        if y.get("fy"):
            fys.append(y["fy"])
    fys.sort()
    total = cert + den + wd
    adj = cert + den
    return {"cert": cert, "denied": den, "withdrawn": wd, "total": total, "adjudicated": adj,
            "rate": pct(cert, adj) if adj else None,
            "firstFy": fys[0] if fys else None, "lastFy": fys[-1] if fys else None}


def live_stats(live: Optional[dict]) -> dict:
    if not live:
        return {"tracked": 0, "pending": 0, "certified": 0, "denied": 0, "withdrawn": 0, "rfi": 0, "audit": 0, "rate": None, "statuses": {}}
    s = live.get("statuses") or {}
    cert = s.get("CERTIFIED", 0) + s.get("CERTIFIED - EXPIRED", 0)
    den = s.get("DENIED", 0)
    wd = s.get("WITHDRAWN", 0)
    rfi = s.get("RFI ISSUED", 0)
    ar = s.get("ANALYST REVIEW", 0)
    audit = s.get("AUDIT REVIEW", 0) + s.get("PENDING AUDIT RESPONSE", 0) + s.get("SUPERVISED RECRUITMENT", 0)
    pending = ar + rfi + audit
    tracked = sum(v for v in s.values() if isinstance(v, int))
    return {"tracked": tracked, "pending": pending, "certified": cert, "denied": den, "withdrawn": wd,
            "rfi": rfi, "ar": ar, "audit": audit, "rate": pct(cert, cert + den) if (cert + den) else None,
            "statuses": s, "first": live.get("firstFiling") or "", "last": live.get("lastFiling") or ""}


def above_pw_pct(h1b: dict) -> Optional[int]:
    above = cmp = 0
    for s in h1b.get("socs") or []:
        if s.get("wage_median") is not None and s.get("pw_median"):
            cmp += s.get("n") or 0
            if s["wage_median"] >= s["pw_median"]:
                above += s.get("n") or 0
    return int(round(above / cmp * 100)) if cmp else None


def fingerprint(m: dict, extras_entry: Optional[dict] = None) -> str:
    """Hash of everything that changes a page's numbers (worker data, rank, offline extras)."""
    core = {k: m.get(k) for k in ("name", "rank", "perm", "lca", "total", "h1b", "live")}
    core["extras"] = extras_entry
    return hashlib.sha1(json.dumps(core, sort_keys=True, separators=(",", ":")).encode()).hexdigest()[:16]


# ── page pieces ──────────────────────────────────────────────────────────────
CSS = """
  * { margin: 0; padding: 0; box-sizing: border-box; }
  :root {
    --bg-html: #0a0a12; --bg-body: #0a0a12; --text-primary: #f0f0f8; --text-secondary: #94a3b8; --text-muted: #64748b; --text-dim: #475569;
    --card-bg: rgba(255,255,255,0.04); --card-border: rgba(255,255,255,0.06);
    --nav-bg: rgba(255,255,255,0.03); --nav-border: rgba(255,255,255,0.06);
    --sep: rgba(255,255,255,0.06);
    --gradient-start: rgba(59,130,246,0.08); --gradient-end: rgba(139,92,246,0.06);
  }
  html.light {
    --bg-html: #f5f7fa; --bg-body: #f5f7fa; --text-primary: #1a1a2e; --text-secondary: #475569; --text-muted: #64748b; --text-dim: #94a3b8;
    --card-bg: rgba(255,255,255,0.85); --card-border: rgba(0,0,0,0.08);
    --nav-bg: rgba(255,255,255,0.85); --nav-border: rgba(0,0,0,0.08);
    --sep: rgba(0,0,0,0.08);
    --gradient-start: transparent; --gradient-end: transparent;
  }
  html { background: var(--bg-html); }
  body { font-family: 'Inter', -apple-system, sans-serif; background: var(--bg-body); color: var(--text-primary); min-height: 100vh; min-width: 100%; overflow-x: hidden; }
  body::before { content: ''; position: fixed; top: -50%; left: -50%; width: 200%; height: 200%; background: radial-gradient(ellipse at 30% 20%, var(--gradient-start) 0%, transparent 50%), radial-gradient(ellipse at 70% 80%, var(--gradient-end) 0%, transparent 50%); z-index: 0; pointer-events: none; }
  .container { position: relative; z-index: 1; max-width: 880px; margin: 0 auto; padding: 0 24px; }
  nav { display: flex; align-items: center; justify-content: space-between; padding: 16px 24px; backdrop-filter: blur(20px); background: var(--nav-bg); border-bottom: 1px solid var(--nav-border); position: sticky; top: 0; z-index: 100; }
  .logo { display: flex; align-items: center; gap: 10px; font-size: 20px; font-weight: 700; letter-spacing: -0.5px; white-space: nowrap; flex-shrink: 0; }
  .logo a { color: inherit; text-decoration: none; display: flex; align-items: center; gap: 10px; }
  .logo-icon { width: 32px; height: 32px; background: linear-gradient(135deg, #3b82f6, #8b5cf6); border-radius: 8px; display: flex; align-items: center; justify-content: center; font-size: 16px; }
  .nav-right { display: flex; align-items: center; gap: 16px; min-width: 0; }
  .nav-links { display: flex; gap: clamp(12px, 1.4vw, 24px); list-style: none; min-width: 0; }
  .nav-links a { color: var(--text-secondary); text-decoration: none; font-size: 14px; font-weight: 500; transition: color 0.2s; white-space: nowrap; }
  .nav-links a.active, .nav-links a:hover { color: var(--text-primary); }
  .nav-toggle { display: none; background: none; border: 1px solid var(--card-border); border-radius: 8px; color: var(--text-primary); font-size: 22px; cursor: pointer; padding: 4px 8px; line-height: 1; }
  .nav-utils { display: flex; align-items: center; gap: 12px; padding-left: 16px; border-left: 1px solid var(--nav-border); flex-shrink: 0; }
  @media (max-width: 1140px) { .nav-utils { border-left: none; padding-left: 0; gap: 10px; } }
  @media (max-width: 1140px) {
    .nav-toggle { display: flex; align-items: center; justify-content: center; order: -1; }
    nav .nav-links { display: none; position: absolute; top: 100%; left: 0; right: 0; flex-direction: column; gap: 0; background: #0f172a; border-bottom: 1px solid rgba(59, 130, 246, 0.2); padding: 8px 0; z-index: 1000; width: 100%; box-shadow: 0 4px 12px rgba(0,0,0,0.3); }
    nav .nav-links li { width: 100%; }
    nav .nav-links a { display: block; padding: 14px 24px; font-size: 15px; border-radius: 0; min-height: 44px; white-space: normal; box-sizing: border-box; }
    nav .nav-links a:hover, nav .nav-links a.active { background: rgba(59,130,246,0.1); }
    nav.nav-open .nav-links { display: flex; }
    .light nav .nav-links { background: #ffffff; border-bottom: 1px solid rgba(0,0,0,0.1); box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
  }
  @media (max-width: 768px) {
    .hero .eyebrow { font-size: 12px; letter-spacing: 1px; }
    .hero h1 { font-size: 20px; }
  }
  footer { text-align: center; padding: 32px 24px; color: var(--text-dim); font-size: 12px; border-top: 1px solid var(--sep); margin-top: 0; position: relative; z-index: 1; }
  footer a { color: var(--text-muted); text-decoration: none; }
  footer a:hover { color: var(--text-secondary); }
  .hero { padding: 40px 0 20px; }
  .hero .eyebrow { font-size: 14px; font-weight: 500; color: #64748b; text-transform: uppercase; letter-spacing: 1.5px; margin-bottom: 8px; }
  .hero h1 { font-size: 28px; font-weight: 700; letter-spacing: -0.5px; background: linear-gradient(135deg, var(--text-primary), var(--text-secondary)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
  .hero .lede { margin-top: 12px; color: var(--text-secondary); font-size: 15px; line-height: 1.7; max-width: 680px; }
  .hero .lede b { color: var(--text-primary); font-weight: 600; }
  .theme-toggle { background: none; border: 1px solid var(--card-border); border-radius: 10px; padding: 8px; cursor: pointer; display: flex; align-items: center; justify-content: center; width: 36px; height: 36px; transition: border-color 0.2s; }
  .theme-toggle:hover { border-color: var(--text-muted); }
  .theme-toggle-icon { font-size: 16px; line-height: 1; }
  .theme-toggle-icon.sun { display: none; }
  html.light .theme-toggle-icon.moon { display: none; }
  html.light .theme-toggle-icon.sun { display: inline; }
  .content { background: var(--card-bg); border: 1px solid var(--card-border); border-radius: 16px; padding: 32px; margin: 24px 0 40px; line-height: 1.8; }
  .content h2 { font-size: 18px; font-weight: 600; margin: 30px 0 12px; color: var(--text-primary); }
  .content h2:first-child { margin-top: 0; }
  .content h3 { font-size: 15px; font-weight: 600; margin: 18px 0 8px; color: var(--text-primary); }
  .content p { font-size: 14px; color: var(--text-secondary); margin-bottom: 12px; }
  .content ul, .content ol { padding-left: 24px; margin-bottom: 12px; }
  .content li { font-size: 14px; color: var(--text-secondary); margin-bottom: 6px; }
  .content a { color: #3b82f6; text-decoration: none; }
  .content a:hover { text-decoration: underline; }
  .content strong, .content b { color: var(--text-primary); }
  .dt-wrap { overflow-x: auto; -webkit-overflow-scrolling: touch; margin: 8px 0 18px; }
  .content table.dt { width: 100%; border-collapse: collapse; font-size: 13.5px; min-width: 480px; }
  .content .dt th, .content .dt td { text-align: left; padding: 9px 12px; border-bottom: 1px solid var(--sep); color: var(--text-secondary); vertical-align: top; white-space: nowrap; }
  .content .dt th { color: var(--text-primary); font-weight: 600; }
  .content .dt td.num, .content .dt th.num { text-align: right; font-variant-numeric: tabular-nums; }
  .content .dt td.txt { white-space: normal; min-width: 180px; }
  .content .dt tr.partial td { color: var(--text-muted); }
  .stat-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 4px 0 8px; }
  .stat { background: var(--card-bg); border: 1px solid var(--card-border); border-radius: 12px; padding: 14px 16px; }
  .stat .l { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: var(--text-muted); font-weight: 600; }
  .stat .v { font-size: 24px; font-weight: 700; color: var(--text-primary); line-height: 1.3; margin-top: 4px; }
  .stat .s { font-size: 12px; color: var(--text-secondary); margin-top: 2px; line-height: 1.5; }
  .stat .v.good { color: #22c55e; } .stat .v.med { color: #f59e0b; } .stat .v.bad { color: #ef4444; } .stat .v.live { color: #f59e0b; }
  .status-list { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px 16px; margin: 6px 0 14px; padding: 0; list-style: none; }
  .status-list li { font-size: 13.5px; color: var(--text-secondary); display: flex; justify-content: space-between; border-bottom: 1px dashed var(--sep); padding: 4px 0; }
  .status-list li b { font-variant-numeric: tabular-nums; }
  .chips { display: flex; flex-wrap: wrap; gap: 8px; margin: 6px 0 14px; }
  .chips a, .chips span { font-size: 12.5px; padding: 5px 10px; border: 1px solid var(--card-border); border-radius: 999px; color: var(--text-secondary); background: var(--card-bg); text-decoration: none; }
  .chips a:hover { border-color: rgba(59,130,246,0.4); color: var(--text-primary); text-decoration: none; }
  .note { background: rgba(59,130,246,0.06); border-left: 3px solid #3b82f6; border-radius: 0 8px 8px 0; padding: 12px 16px; margin: 8px 0 16px; }
  .note p { margin-bottom: 0; font-size: 13.5px; }
  .cta-box { background: linear-gradient(135deg, rgba(59,130,246,0.1), rgba(139,92,246,0.08)); border: 1px solid rgba(59,130,246,0.2); border-radius: 12px; padding: 20px 24px; margin-top: 24px; }
  .cta-box p { margin-bottom: 0; }
  .cta-box a { font-weight: 600; }
  .faq h3 { margin-top: 16px; }
  .disclaimer { font-size: 12.5px; color: var(--text-muted); font-style: italic; margin-top: 24px; padding-top: 16px; border-top: 1px solid var(--sep); }
  .sources { font-size: 12.5px; color: var(--text-muted); margin-top: 18px; }
  .breadcrumb { font-size: 12.5px; color: var(--text-muted); margin-top: 28px; }
  .breadcrumb a { color: var(--text-muted); text-decoration: none; }
  .breadcrumb a:hover { color: var(--text-secondary); }
  .az-nav { display: flex; flex-wrap: wrap; gap: 6px; margin: 8px 0 16px; }
  .az-nav a { font-size: 12.5px; padding: 4px 9px; border: 1px solid var(--card-border); border-radius: 8px; color: var(--text-secondary); text-decoration: none; }
  .az-nav span { font-size: 12.5px; padding: 4px 9px; border: 1px solid transparent; color: var(--text-dim); }
  .az-group { margin: 14px 0; }
  .az-group h3 { margin: 0 0 6px; font-size: 14px; color: var(--text-muted); }
  .az-group ul { list-style: none; padding: 0; columns: 2; column-gap: 24px; }
  .az-group li { font-size: 13.5px; break-inside: avoid; }
  @media (max-width: 768px) {
    .container { padding: 0 14px; }
    nav { padding: 12px 14px; flex-wrap: wrap; row-gap: 8px; }
    .logo { font-size: 18px; }
    .logo-icon { width: 28px; height: 28px; font-size: 14px; }
    .hero { padding: 24px 0 14px; }
    .content { padding: 24px 18px; }
    .stat-grid { grid-template-columns: repeat(2, 1fr); }
    .status-list { grid-template-columns: 1fr 1fr; }
    .az-group ul { columns: 1; }
  }
"""

HEAD_TOP = """<!DOCTYPE html>
<html lang="en">
<head>
<script type="text/javascript" src="//monu.delivery/site/6/7/24ec8e-ce2f-4a85-ba1a-e1a4ecaea496.js" data-cfasync="false"></script>
<!-- ImmiLane: collapse EMPTY Monumetric ad slots until a real ad fills them (added 2026-06-24). Removes blank reserved gaps while ads are unfilled; reveals each slot at its reserved size the moment a creative loads. Does not touch the loader or ad-unit ids. -->
<style id="mmt-empty-collapse-css">div[id^="mmt-"]:not([data-mmt-filled]){min-height:0}</style>
<script id="mmt-empty-collapse">
(function(){
  var SEL='div[id^="mmt-"][id$="_zone"], div[id^="mmt-"][id$="_placeholder"]';
  function realAd(z){
    var f=z.getElementsByTagName('iframe');
    for(var i=0;i<f.length;i++){var r=f[i].getBoundingClientRect();if(r.height>1&&r.width>1)return true;}
    return false;
  }
  function sweep(){
    var z=document.querySelectorAll(SEL);
    for(var i=0;i<z.length;i++){
      var el=z[i];
      if(el.getAttribute('data-mmt-filled')==='1')continue;
      if(realAd(el)){
        el.setAttribute('data-mmt-filled','1');
        var o=el.getAttribute('data-mmt-orig-mh');
        if(o)el.style.setProperty('min-height',o,'important');
        else el.style.removeProperty('min-height');
        continue;
      }
      if(el.getAttribute('data-mmt-collapsed')!=='1'){
        el.setAttribute('data-mmt-orig-mh',el.style.getPropertyValue('min-height'));
        el.setAttribute('data-mmt-collapsed','1');
      }
      var cur=el.style.getPropertyValue('min-height');
      if(cur!=='0px'&&cur!=='0')el.style.setProperty('min-height','0','important');
    }
  }
  function start(){
    sweep();
    try{new MutationObserver(sweep).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['style','id']});}catch(e){}
    var n=0,iv=setInterval(function(){sweep();if(++n>120)clearInterval(iv);},1000);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);
  else start();
})();
</script>
<meta charset="UTF-8">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="icon" type="image/x-icon" href="/favicon.ico">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
"""

HEAD_BOTTOM = """<script async src="https://www.googletagmanager.com/gtag/js?id=G-G8NXS7DNX1"></script>
<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-G8NXS7DNX1');</script>
<script>if(localStorage.getItem('theme')==='light')document.documentElement.classList.add('light');</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap">
<style>""" + CSS + """</style>
</head>
"""

BODY_TOP = """<body>
<!-- Monumetric anchored ad units (self-positioning via loader) — BEGIN -->
<!-- Pillar side rails are gated: the slot divs are only created (and only then
     registered with Monumetric) when the viewport is at least PILLAR_MIN_WIDTH px
     wide. Below that the divs never exist, so no ad is requested — laptops get a
     clean full-width dashboard, wide monitors serve pillars exactly as before. -->
<script type="text/javascript" data-cfasync="false">
(function () {
  var PILLAR_MIN_WIDTH = 1840; // px — pillars need ~300px per side; only fits on wide external monitors
  if (window.innerWidth < PILLAR_MIN_WIDTH) return;
  var pillars = [
    "b49d4117-779e-4093-bc4b-04a427fc102d", /* Pillar - Right */
    "1de40a31-0af3-4522-be14-84d8900c57b0"  /* Pillar - Left */
  ];
  var here = document.currentScript;
  $MMT = window.$MMT || {}; $MMT.cmd = $MMT.cmd || [];
  pillars.forEach(function (uuid) {
    var d = document.createElement("div");
    d.id = "mmt-" + uuid;
    here.parentNode.insertBefore(d, here);
    $MMT.cmd.push(function () { $MMT.display.slots.push([uuid]); });
  });
})();
</script>
<div id="mmt-2ebba6a6-83c2-44c0-9ad4-9c1ded6e4511"></div>
<script type="text/javascript" data-cfasync="false">$MMT = window.$MMT || {}; $MMT.cmd = $MMT.cmd || []; $MMT.cmd.push(function(){ $MMT.display.slots.push(["2ebba6a6-83c2-44c0-9ad4-9c1ded6e4511"]); })</script>
<div id="mmt-d33dabc7-369a-4126-8a86-ff0f346c42ea"></div>
<script type="text/javascript" data-cfasync="false">$MMT = window.$MMT || {}; $MMT.cmd = $MMT.cmd || []; $MMT.cmd.push(function(){ $MMT.display.slots.push(["d33dabc7-369a-4126-8a86-ff0f346c42ea"]); })</script>
<div id="mmt-4b3cdef0-e13a-48ab-bff9-b996ba62c869"></div>
<script type="text/javascript" data-cfasync="false">$MMT = window.$MMT || {}; $MMT.cmd = $MMT.cmd || []; $MMT.cmd.push(function(){ $MMT.display.slots.push(["4b3cdef0-e13a-48ab-bff9-b996ba62c869"]); })</script>
<!-- Monumetric anchored ad units — END -->
<nav>
  <div class="logo"><a href="/"><div class="logo-icon">&#127963;&#65039;</div>PERM Tracker</a></div>
  <button class="nav-toggle" id="nav-toggle" aria-label="Open menu">&#9776;</button>
  <div class="nav-right">
    <ul class="nav-links">
      <li><a href="/">Dashboard</a></li>
      <li><a href="/estimate">Estimate</a></li>
      <li><a href="/leaderboard" class="active">Top Employers</a></li>
      <li><a href="/visa-bulletin">Visa Bulletin</a></li>
      <li><a href="/guides">Guides</a></li>
      <li><a href="/subscribe">Case Watch</a></li>
      <li><a href="/about-perm">About PERM</a></li>
      <li><a href="/faq">FAQ</a></li>
    </ul>
    <div class="nav-utils"><button class="theme-toggle" id="theme-toggle" aria-label="Toggle light/dark mode"><span class="theme-toggle-icon moon">&#127769;</span><span class="theme-toggle-icon sun">&#9728;&#65039;</span></button></div>
  </div>
</nav>
"""

IN_CONTENT_AD = """
    <!-- Monumetric In-Content Repeatable ad unit — BEGIN -->
    <div id="mmt-a0e6cd6c-321d-4e87-97a2-f2eb855508e5"></div>
    <script type="text/javascript" data-cfasync="false">$MMT = window.$MMT || {}; $MMT.cmd = $MMT.cmd || []; $MMT.cmd.push(function(){ $MMT.display.slots.push(["a0e6cd6c-321d-4e87-97a2-f2eb855508e5"]); })</script>
    <!-- Monumetric In-Content Repeatable ad unit — END -->
"""

FOOTER = """<footer>
  Data sourced from <a href="https://flag.dol.gov/programs/lca" target="_blank" rel="noopener">FLAG.DOL.GOV</a> &middot; Updated daily &middot; <a href="/guides">Guides</a> &middot; <a href="/about-us">About</a> &middot; <a href="/support">Contact</a> &middot; <a href="/privacy">Privacy</a> &middot; <a href="/terms">Terms</a> &middot; <a href="/refund">Refund</a> &middot; <a href="/disclaimer">Disclaimer</a> &middot; <br><a href="/perm-status-check">PERM Status Check</a> &middot; <a href="/perm-case-status">Case Status Meanings</a> &middot; <a href="/dol-case-status">DOL Case Status</a> &middot; <a href="/perm-processing-time">Processing Times</a> &middot; <a href="/employers">Employer Profiles</a> &middot; &copy; 2026 ImmiLane
</footer>

<script>
document.getElementById('theme-toggle').addEventListener('click', function() {
  document.documentElement.classList.toggle('light');
  localStorage.setItem('theme', document.documentElement.classList.contains('light') ? 'light' : 'dark');
});
document.getElementById('nav-toggle').addEventListener('click', function() {
  document.querySelector('nav').classList.toggle('nav-open');
});
</script>
"""


def shared_widgets(root: str) -> str:
    """Feedback widget + session-check + Case Watch strip, copied verbatim from the
    guide template so every page shares the same behaviour; relative hrefs made
    absolute because these pages live one directory deeper."""
    src = open(os.path.join(root, "guide-how-dol-processes-perm.html"), encoding="utf-8").read()
    m = re.search(r"(<!-- Feedback Widget \(shared across all pages\) -->.*?<!-- il-cw-announce END -->)", src, re.S)
    if not m:
        raise RuntimeError("shared widget block not found in guide template")
    block = m.group(1)
    block = block.replace('href="subscribe"', 'href="/subscribe"')
    return block


# ── employer page ────────────────────────────────────────────────────────────
def build_page(m: dict, ctx: dict) -> str:
    name = m["name"]
    slug = m["slug"]
    h1b = m.get("h1b") or {}
    ps = perm_stats(h1b)
    ls = live_stats(m.get("live"))
    dash = ctx["dash"]
    extras = (ctx.get("extras") or {}).get("employers", {}).get(slug)
    rank = m.get("rank")
    total_emp = ctx["index"].get("totalEmployers")
    url = f"{SITE}/employers/{slug}"
    fy_first, fy_last = ps["firstFy"], ps["lastFy"]
    perm_total = ps["total"]
    rate = ps["rate"]
    live_meta_ts = (ctx.get("liveMeta") or {}).get("generatedAt")
    h1b_fy = h1b.get("fy") or "FY2025"
    med_wage = h1b.get("wage_median_all")
    above = above_pw_pct(h1b)
    lca_total = sum((y.get("total") or 0) for y in h1b.get("lcaByYear") or [])
    titles = h1b.get("permTitlesAll") or []
    frontier = dash["frontier"]

    # ── title / description ────────────────────────────────────────────
    # Title: the searchable part ("<Employer> PERM & Green Card") first, then the
    # two numbers people compare, then the brand — long names simply truncate at
    # the brand end in SERPs.
    title_bits = [f"{n(perm_total)} Cases"]
    if rate is not None:
        title_bits.append(f"{fmt_pct(rate, 0)} Certified")
    title = f"{name} PERM & Green Card: {', '.join(title_bits)} | ImmiLane"
    desc_parts = [f"{name} has {n(perm_total)} PERM (green card) labor certification cases in DOL data"
                  + (f" ({fy_first}–{fy_last})" if fy_first and fy_last else "")
                  + (f", {fmt_pct(rate)} certified" if rate is not None else "") + "."]
    if ls["tracked"]:
        desc_parts.append(f"{n(ls['pending'])} now pending with DOL.")
    if med_wage:
        desc_parts.append(f"Median H-1B salary {usd(med_wage)} ({h1b_fy}).")
    desc = " ".join(desc_parts)
    if len(desc) < 120:
        desc += " Cases by year, job titles, wages and FAQs."

    # ── lede ───────────────────────────────────────────────────────────
    lede = (f"<b>{esc(name)}</b> has filed <b>{n(perm_total)}</b> PERM (green-card) labor certification applications "
            f"with the U.S. Department of Labor"
            + (f" between <b>{esc(fy_short(fy_first))}</b> and <b>{esc(fy_short(fy_last))}</b>" if fy_first and fy_last else "")
            + (f", with <b>{fmt_pct(rate)}</b> of adjudicated cases certified" if rate is not None else "") + ".")
    if rank and total_emp:
        lede += f" That makes it the <b>#{n(rank)}</b> PERM sponsor of {n(total_emp)} employers in DOL disclosure data."
    if ls["tracked"]:
        lede += (f" The live tracker shows <b>{n(ls['pending'])}</b> of its recent filings still pending with DOL"
                 f" (DOL is currently adjudicating <b>{esc(frontier)}</b> filings).")

    # ── key stats ──────────────────────────────────────────────────────
    rate_cls = "" if rate is None else ("good" if rate > 80 else "med" if rate >= 60 else "bad")
    stats = [
        ("PERM filings", n(perm_total), f"{esc(fy_short(fy_first))} – {esc(fy_short(fy_last))}" if fy_first else "DOL disclosure data", ""),
        ("Certification rate", fmt_pct(rate), f"{n(ps['cert'])} certified of {n(ps['adjudicated'])} adjudicated" if ps["adjudicated"] else "No adjudicated cases", rate_cls),
        ("Pending with DOL", n(ls["pending"]) if ls["tracked"] else "—",
         (f"live tracker · {n(ls['tracked'])} filings since {esc(fmt_month(ls['first']))}" if ls["tracked"] else "not in the live tracker"), "live" if ls["tracked"] else ""),
        ("Median H-1B salary", usd(med_wage), (f"{n(h1b.get('total'))} certified LCAs · {esc(h1b_fy)}" if h1b.get("total") else f"no {esc(h1b_fy)} LCA data"), ""),
    ]
    stats_html = '<div class="stat-grid" id="key-stats">' + "".join(
        f'<div class="stat"><div class="l">{esc(l)}</div><div class="v {c}">{v}</div><div class="s">{s}</div></div>'
        for l, v, s, c in stats) + "</div>"

    # ── PERM by year table ─────────────────────────────────────────────
    rows = []
    for y in sorted(h1b.get("permByYear") or [], key=lambda y: y.get("fy") or ""):
        c, d, w = y.get("cert") or 0, y.get("denied") or 0, y.get("withdrawn") or 0
        r = pct(c, c + d) if (c + d) else None
        cls = ' class="partial"' if y.get("partial") else ""
        rows.append(f"<tr{cls}><td>{esc(fy_short(y.get('fy')))}{' <small>(year-to-date)</small>' if y.get('partial') else ''}</td>"
                    f"<td class=\"num\">{n(c + d + w)}</td><td class=\"num\">{n(c)}</td><td class=\"num\">{n(d)}</td>"
                    f"<td class=\"num\">{n(w)}</td><td class=\"num\">{fmt_pct(r)}</td><td class=\"num\">{usd(y.get('salary_median'))}</td></tr>")
    rows.append(f"<tr><th>All years</th><th class=\"num\">{n(perm_total)}</th><th class=\"num\">{n(ps['cert'])}</th>"
                f"<th class=\"num\">{n(ps['denied'])}</th><th class=\"num\">{n(ps['withdrawn'])}</th><th class=\"num\">{fmt_pct(rate)}</th><th class=\"num\">—</th></tr>")
    perm_table = ('<div class="dt-wrap"><table class="dt" id="perm-by-year-table"><thead><tr><th>Fiscal year</th><th class="num">Cases</th><th class="num">Certified</th>'
                  '<th class="num">Denied</th><th class="num">Withdrawn</th><th class="num">Cert. rate</th><th class="num">Median offered wage</th></tr></thead>'
                  f'<tbody>{"".join(rows)}</tbody></table></div>')

    # recent-years summary sentence (last 3 complete FYs)
    complete = [y for y in sorted(h1b.get("permByYear") or [], key=lambda y: y.get("fy") or "") if not y.get("partial")]
    recent = complete[-3:]
    recent_txt = ""
    if recent:
        parts = [f"{esc(fy_short(y['fy']))}: {n((y.get('cert') or 0) + (y.get('denied') or 0) + (y.get('withdrawn') or 0))}" for y in recent]
        peak = max(h1b.get("permByYear") or [], key=lambda y: (y.get("cert") or 0) + (y.get("denied") or 0) + (y.get("withdrawn") or 0))
        peak_n = (peak.get("cert") or 0) + (peak.get("denied") or 0) + (peak.get("withdrawn") or 0)
        recent_txt = (f"<p>Recent volume — {', '.join(parts)} cases. The busiest year on record was <b>{esc(fy_short(peak.get('fy')))}</b> "
                      f"with <b>{n(peak_n)}</b> cases decided.</p>")

    # ── live status section ────────────────────────────────────────────
    if ls["tracked"]:
        order = [("CERTIFIED", "Certified"), ("ANALYST REVIEW", "Analyst review"), ("RFI ISSUED", "RFI issued"),
                 ("AUDIT REVIEW", "Audit review"), ("PENDING AUDIT RESPONSE", "Pending audit response"),
                 ("SUPERVISED RECRUITMENT", "Supervised recruitment"), ("DENIED", "Denied"), ("WITHDRAWN", "Withdrawn"),
                 ("CERTIFIED - EXPIRED", "Certified (expired)")]
        items = "".join(f"<li><span>{lbl}</span><b>{n(ls['statuses'][k])}</b></li>" for k, lbl in order if ls["statuses"].get(k))
        live_html = (
            f"<p>ImmiLane's case-status tracker re-scans DOL's public PERM records several times a day for cases filed since "
            f"{esc(fmt_month(ls['first']))}. For {esc(name)} it currently tracks <b>{n(ls['tracked'])}</b> filings: "
            f"<b>{n(ls['certified'])}</b> certified, <b>{n(ls['pending'])}</b> still pending"
            + (f" ({n(ls['ar'])} in analyst review" + (f", {n(ls['rfi'])} with an RFI" if ls['rfi'] else "") + (f", {n(ls['audit'])} in audit" if ls['audit'] else "") + ")" if ls['pending'] else "")
            + f", <b>{n(ls['denied'])}</b> denied and <b>{n(ls['withdrawn'])}</b> withdrawn."
            + (f" Certification rate among decided cases: <b>{fmt_pct(ls['rate'])}</b>." if ls['rate'] is not None else "")
            + f" Most recent filing seen: <b>{esc(fmt_date(ls['last']))}</b>.</p>"
            f'<ul class="status-list" id="live-status-list">{items}</ul>'
            + (f"<p>DOL is currently adjudicating <b>{esc(frontier)}</b> filings ({esc(dash['pct'])} of that month processed, "
               f"{esc(dash['remain'])} cases remaining) — see the <a href=\"/perm-processing-time\">live PERM processing time tracker</a>. "
               f"Live tracker data as of {esc(fmt_et_long(live_meta_ts))}.</p>" if live_meta_ts else "")
        )
        tt = [t for t in ((m.get("live") or {}).get("topTitles") or []) if t.get("title")]
        if tt:
            live_html += "<p>Job titles in these recent filings: " + ", ".join(f"{esc(t['title'].strip())} ({n(t['count'])})" for t in tt[:6]) + ".</p>"
    else:
        live_html = (f"<p>{esc(name)} has no cases in ImmiLane's live case-status tracker, which follows PERM applications filed since "
                     f"November 2024. Its historical filings above come from DOL's annual disclosure files.</p>")

    # ── processing time ────────────────────────────────────────────────
    proc_html = (f"<p>DOL adjudicates PERM applications in filing-date order, not by employer, so a case from {esc(name)} waits in the same "
                 f"queue as every other case filed the same month. As of {esc(dash['updated'])}, DOL is working on <b>{esc(frontier)}</b> filings "
                 f"and recently decided cases averaged <b>{esc(dash['avg'])} days</b> from filing to decision "
                 f"(certified cases {esc(dash['avgCert'])} days). Audited cases take longer — see the "
                 f"<a href=\"/guide-perm-audits-rfis\">PERM audits and RFIs guide</a>.</p>")
    proc_rows = ""
    if extras and extras.get("proc"):
        rws = []
        for fy in sorted(extras["proc"]):
            p = extras["proc"][fy]
            if (p.get("n") or 0) < 5:
                continue
            rws.append(f"<tr><td>{esc(fy_short(fy))}</td><td class=\"num\">{n(p['n'])}</td><td class=\"num\">{n(p['median'])}</td>"
                       f"<td class=\"num\">{n(p.get('p25'))}</td><td class=\"num\">{n(p.get('p75'))}</td></tr>")
        if rws:
            proc_rows = ('<p>Filing-to-decision times for this employer\'s <b>certified</b> PERM cases, by the fiscal year of the DOL decision '
                         '(from DOL\'s PERM disclosure files):</p>'
                         '<div class="dt-wrap"><table class="dt" id="proc-table"><thead><tr><th>Decision FY</th><th class="num">Certified cases</th>'
                         '<th class="num">Median days</th><th class="num">25th pct.</th><th class="num">75th pct.</th></tr></thead>'
                         f'<tbody>{"".join(rws)}</tbody></table></div>')
    proc_html += proc_rows + (f"<p>Estimate your own case with the <a href=\"/estimate\">PERM estimate tool</a>, or get an email when it "
                             f"changes status with <a href=\"/subscribe\">Case Watch</a>.</p>")

    # ── job titles ─────────────────────────────────────────────────────
    if titles:
        tot_t = sum(t.get("n") or 0 for t in titles)
        trows = "".join(f"<tr><td class=\"txt\">{esc(t['title'])}</td><td class=\"num\">{n(t.get('n'))}</td></tr>" for t in titles)
        titles_html = (f"<p>The most common job titles on {esc(name)}'s PERM applications (FY2020–{esc(fy_last or 'FY2026')} disclosure data; "
                       f"top {len(titles)} titles, {n(tot_t)} cases):</p>"
                       '<div class="dt-wrap"><table class="dt" id="titles-table"><thead><tr><th>PERM job title</th><th class="num">Cases</th></tr></thead>'
                       f'<tbody>{trows}</tbody></table></div>')
    else:
        titles_html = "<p>No job-title breakdown is available for this employer in the disclosure data.</p>"

    # ── locations ──────────────────────────────────────────────────────
    loc_html = ""
    if extras and (extras.get("states") or extras.get("cities")):
        win = (ctx.get("extras") or {}).get("window", "FY2020 – FY2026")
        tot_rows = extras.get("n_rows") or 0
        srows = "".join(f"<tr><td>{esc(s[0])}</td><td class=\"num\">{n(s[1])}</td><td class=\"num\">{fmt_pct(pct(s[1], tot_rows))}</td></tr>" for s in extras.get("states") or [])
        crows = "".join(f"<tr><td class=\"txt\">{esc(c[0])}, {esc(c[1])}</td><td class=\"num\">{n(c[2])}</td><td class=\"num\">{fmt_pct(pct(c[2], tot_rows))}</td></tr>" for c in extras.get("cities") or [])
        loc_html = (f"<p>Primary worksite locations on {esc(name)}'s PERM applications, from DOL's PERM disclosure files for decisions in {esc(win)} ({n(tot_rows)} cases):</p>"
                    '<div class="dt-wrap"><table class="dt" id="states-table"><thead><tr><th>Worksite state</th><th class="num">Cases</th><th class="num">Share</th></tr></thead>'
                    f'<tbody>{srows}</tbody></table></div>'
                    '<div class="dt-wrap"><table class="dt" id="cities-table"><thead><tr><th>Worksite city</th><th class="num">Cases</th><th class="num">Share</th></tr></thead>'
                    f'<tbody>{crows}</tbody></table></div>')

    # ── H-1B section ───────────────────────────────────────────────────
    socs = h1b.get("socs") or []
    if h1b.get("total") and socs:
        srows = "".join(
            f"<tr><td class=\"txt\">{esc(s.get('title') or s.get('soc'))}<br><small>SOC {esc(s.get('soc'))}</small></td><td class=\"num\">{n(s.get('n'))}</td>"
            f"<td class=\"num\">{usd(s.get('wage_p10'))}</td><td class=\"num\">{usd(s.get('wage_median'))}</td><td class=\"num\">{usd(s.get('wage_p90'))}</td>"
            f"<td class=\"num\">{usd(s.get('pw_median'))}</td></tr>" for s in socs)
        h1b_html = (f"<p>In {esc(h1b_fy)}, {esc(name)} had <b>{n(h1b.get('total'))}</b> certified H-1B Labor Condition Application (LCA) positions "
                    f"with a median offered salary of <b>{usd(med_wage)}</b>"
                    + (f"; about <b>{above}%</b> of those positions were offered at or above the DOL prevailing wage" if above is not None else "") + ". "
                    f"Across all years on record ({esc(fy_short((h1b.get('lcaByYear') or [{}])[0].get('fy') or 'FY2008'))} onward) it has <b>{n(lca_total)}</b> LCA filings.</p>"
                    f"<p>Top H-1B occupations by offered wage ({esc(h1b_fy)}, top {len(socs)}):</p>"
                    '<div class="dt-wrap"><table class="dt" id="h1b-soc-table"><thead><tr><th>Occupation</th><th class="num">LCAs</th><th class="num">10th pct.</th>'
                    '<th class="num">Median</th><th class="num">90th pct.</th><th class="num">Prevailing (median)</th></tr></thead>'
                    f'<tbody>{srows}</tbody></table></div>')
    else:
        h1b_html = f"<p>No certified H-1B LCA salary data is on file for {esc(name)} for {esc(h1b_fy)}.</p>"

    # LCA by year (compact)
    lca_rows = []
    for y in sorted(h1b.get("lcaByYear") or [], key=lambda y: y.get("fy") or ""):
        cls = ' class="partial"' if y.get("partial") else ""
        lca_rows.append(f"<tr{cls}><td>{esc(fy_short(y.get('fy')))}{' <small>(year-to-date)</small>' if y.get('partial') else ''}</td><td class=\"num\">{n(y.get('total'))}</td>"
                        f"<td class=\"num\">{n(y.get('cert'))}</td><td class=\"num\">{usd(y.get('wage_median'))}</td><td class=\"num\">{usd(y.get('pw_median'))}</td></tr>")
    lca_table = ('<div class="dt-wrap"><table class="dt" id="lca-by-year-table"><thead><tr><th>Fiscal year</th><th class="num">LCA filings</th><th class="num">Certified</th>'
                 '<th class="num">Median offered wage</th><th class="num">Median prevailing wage</th></tr></thead>'
                 f'<tbody>{"".join(lca_rows)}</tbody></table></div>') if lca_rows else ""

    # ── salary trend ───────────────────────────────────────────────────
    st_rows = []
    for y in sorted(h1b.get("salaryTrend") or [], key=lambda y: y.get("fy") or ""):
        if y.get("h1b_offered") is None and y.get("gc") is None and y.get("prevailing") is None:
            continue
        cls = ' class="partial"' if y.get("partial") else ""
        st_rows.append(f"<tr{cls}><td>{esc(fy_short(y.get('fy')))}</td><td class=\"num\">{usd(y.get('gc'))}</td><td class=\"num\">{usd(y.get('h1b_offered'))}</td><td class=\"num\">{usd(y.get('prevailing'))}</td></tr>")
    trend_html = ('<div class="dt-wrap"><table class="dt" id="salary-trend-table"><thead><tr><th>Fiscal year</th><th class="num">PERM offered wage (median)</th>'
                  '<th class="num">H-1B offered wage (median)</th><th class="num">Prevailing wage (median)</th></tr></thead>'
                  f'<tbody>{"".join(st_rows)}</tbody></table></div>'
                  "<p>Annualized medians of certified filings. PERM (green card) wages come from the ETA-9089 offered wage, H-1B offered and prevailing wages "
                  "from the ETA-9035 LCA disclosure. FY2026 is year-to-date.</p>") if st_rows else ""

    # ── FAQ ────────────────────────────────────────────────────────────
    faqs: List[Tuple[str, str]] = []
    faqs.append((f"Does {name} sponsor green cards?",
                 f"Yes. DOL disclosure data shows {n(perm_total)} PERM labor certification applications from {name}"
                 + (f" between {fy_short(fy_first)} and {fy_short(fy_last)}" if fy_first else "")
                 + ". PERM is the first step of the employer-sponsored (EB-2/EB-3) green card process."
                 + (f" The live tracker also shows {n(ls['pending'])} of its recent filings still pending with DOL." if ls['tracked'] and ls['pending'] else "")))
    faqs.append((f"What is {name}'s PERM approval rate?",
                 (f"{fmt_pct(rate)}: {n(ps['cert'])} of {n(ps['adjudicated'])} adjudicated cases (certified plus denied, withdrawn cases excluded) were certified across all years in DOL disclosure data."
                  if rate is not None else "No adjudicated cases are on record, so a rate cannot be computed.")
                 + (f" Among cases in the live tracker decided since {fmt_month(ls['first'])}, the certification rate is {fmt_pct(ls['rate'])}." if ls.get('rate') is not None else "")))
    faqs.append((f"How long does PERM take at {name}?",
                 f"DOL processes PERM in filing-date order regardless of employer. As of {dash['updated']} it is adjudicating {frontier} filings, and recently decided cases averaged {dash['avg']} days from filing to decision."
                 + ((f" This employer's certified cases decided in {fy_short(max(extras['proc']))} had a median of {n(extras['proc'][max(extras['proc'])]['median'])} days from filing to decision.") if extras and extras.get("proc") and (extras['proc'][max(extras['proc'])].get('n') or 0) >= 5 else "")))
    if titles:
        faqs.append((f"Which jobs does {name} sponsor for green cards?",
                     "The most common PERM job titles are " + ", ".join(t["title"] for t in titles[:5]) + "."))
    if med_wage:
        faqs.append((f"How much does {name} pay H-1B workers?",
                     f"The median offered H-1B salary in {h1b_fy} LCA filings was {usd(med_wage)} across {n(h1b.get('total'))} certified positions"
                     + (f", and about {above}% of positions were at or above the DOL prevailing wage" if above is not None else "") + "."))
    if extras and extras.get("states"):
        faqs.append((f"Where are {name}'s sponsored jobs located?",
                     "The most common primary worksite states on its PERM applications are " + ", ".join(f"{s[0]} ({n(s[1])})" for s in extras["states"][:4]) + "."))
    faq_html = '<div class="faq" id="faq">' + "".join(f"<h3>{esc(q)}</h3><p>{esc(a)}</p>" for q, a in faqs) + "</div>"

    # ── aliases / related ──────────────────────────────────────────────
    aliases = [a for a in (h1b.get("aliasNames") or []) if a and a.strip().lower() != name.strip().lower()]
    alias_html = ("<p>Also filed as: " + ", ".join(f"<span>{esc(a)}</span>" for a in aliases[:6]) + ".</p>") if aliases else ""
    related = ctx["related"].get(slug, [])
    related_html = ('<div class="chips" id="related">' + "".join(
        f'<a href="/employers/{esc(r["slug"])}">{esc(r["name"])} · {n(r.get("permSum", r.get("perm")))}</a>' for r in related) + "</div>") if related else ""

    # ── JSON-LD ────────────────────────────────────────────────────────
    breadcrumb = {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [
        {"@type": "ListItem", "position": 1, "name": "ImmiLane", "item": SITE + "/"},
        {"@type": "ListItem", "position": 2, "name": "Employer PERM Profiles", "item": SITE + "/employers"},
        {"@type": "ListItem", "position": 3, "name": name, "item": url}]}
    dataset = {"@context": "https://schema.org", "@type": "Dataset",
               "name": f"{name} PERM labor certification and H-1B LCA filings",
               "description": f"PERM (green card) labor certification cases by fiscal year, certification rate, job titles, offered wages and H-1B LCA salary data for {name}, compiled from U.S. Department of Labor OFLC disclosure files and ImmiLane's live PERM case-status tracker.",
               "url": url, "license": "https://www.dol.gov/general/aboutdol/copyright", "isAccessibleForFree": True,
               "creator": {"@type": "Organization", "name": "ImmiLane", "url": SITE + "/"},
               "isBasedOn": "https://www.dol.gov/agencies/eta/foreign-labor/performance",
               "temporalCoverage": f"{(fy_first or 'FY2008')[2:]}/{(fy_last or 'FY2026')[2:]}",
               "variableMeasured": ["PERM cases by fiscal year", "PERM certification rate", "PERM job titles", "H-1B LCA offered wages"],
               "dateModified": m.get("lastmod") or today_et().isoformat()}
    faq_ld = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": [
        {"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in faqs]}
    ld = "".join(f'<script type="application/ld+json">{json.dumps(o, ensure_ascii=False)}</script>\n' for o in (breadcrumb, dataset, faq_ld))

    sources = (f"Sources: U.S. Department of Labor, Office of Foreign Labor Certification — PERM (ETA-9089) and LCA (ETA-9035) disclosure files, "
               f"{esc(fy_short(fy_first or 'FY2008'))}–{esc(fy_short(fy_last or 'FY2026'))} (FY2026 year-to-date; fiscal years run October–September and reflect the year of DOL's decision); "
               f"ImmiLane live PERM case-status tracker (filings since November 2024"
               + (f", updated {esc(fmt_et_long(live_meta_ts))}" if live_meta_ts else "") + "). "
               f"Rank is by PERM filing volume among {n(total_emp)} employers in the same disclosure data. Page updated {esc(ctx['generated'])}.")

    head = (HEAD_TOP + f"<title>{esc(title)}</title>\n"
            f'<meta name="description" content="{esc(desc)}">\n'
            f'<link rel="canonical" href="{url}">\n'
            f'<meta property="og:type" content="article">\n<meta property="og:title" content="{esc(title)}">\n'
            f'<meta property="og:description" content="{esc(desc)}">\n<meta property="og:url" content="{url}">\n'
            f'<meta property="og:site_name" content="ImmiLane">\n<meta property="og:locale" content="en_US">\n'
            f'<meta name="twitter:card" content="summary">\n<meta name="twitter:title" content="{esc(title)}">\n'
            f'<meta name="twitter:description" content="{esc(desc)}">\n' + ld + HEAD_BOTTOM)

    body = (BODY_TOP + f"""
<div class="container">
  <div class="hero">
    <div class="eyebrow">Employer &middot; PERM green card sponsorship{(' &middot; #' + n(rank) + ' by filings') if rank else ''}</div>
    <h1>{esc(name)} PERM &amp; Green Card Sponsorship</h1>
    <p class="lede" id="lede">{lede}</p>
  </div>
  <div class="breadcrumb"><a href="/">Dashboard</a> &rsaquo; <a href="/employers">Employer Profiles</a> &rsaquo; {esc(name)}</div>

  <div class="content">
    {stats_html}
    {alias_html}
    <p>Open the <a href="/employer?e={esc(slug)}">interactive profile for {esc(name)}</a> for charts, or browse the <a href="/leaderboard">full employer leaderboard</a>.</p>
{IN_CONTENT_AD}
    <h2 id="perm-by-year">PERM cases by fiscal year</h2>
    <p>Green-card labor certification cases for {esc(name)} as published in DOL's PERM disclosure files. Each fiscal year counts the cases DOL <em>decided</em> that year (certified, denied or withdrawn); the certification rate excludes withdrawn cases. The median offered wage is the annualized wage on certified applications.</p>
    {perm_table}
    {recent_txt}

    <h2 id="live-status">Current PERM case status</h2>
    {live_html}

    <h2 id="processing-time">PERM processing time</h2>
    {proc_html}

    <h2 id="titles">Job titles sponsored</h2>
    {titles_html}
    {('<h2 id="locations">Work locations</h2>' + loc_html) if loc_html else ''}

    <h2 id="h1b">H-1B salaries and LCA filings</h2>
    {h1b_html}
    {lca_table}
    {('<h2 id="salary-trend">Offered wages over time</h2>' + trend_html) if trend_html else ''}

    <h2 id="faq-heading">Frequently asked questions</h2>
    {faq_html}

    {('<h2 id="related-heading">Employers with similar PERM volume</h2>' + related_html) if related_html else ''}
    <p><a href="/employers">All top PERM sponsors</a> &middot; <a href="/leaderboard">Search {n(total_emp)} employers</a> &middot; <a href="/perm-status-check">Check a PERM case status</a> &middot; <a href="/guide-how-dol-processes-perm">How DOL processes PERM</a> &middot; <a href="/guide-eb1-eb2-eb3-explained">EB-1, EB-2 and EB-3 explained</a></p>

    <div class="cta-box"><p>Waiting on a PERM case from {esc(name)}? Track the DOL queue on the <a href="/">live dashboard</a>, estimate your decision window with the <a href="/estimate">estimate tool</a>, or get email alerts with <a href="/subscribe">Case Watch</a>.</p></div>
    <p class="sources" id="sources">{sources}</p>
    <p class="disclaimer">Informational only &mdash; not legal advice. ImmiLane is an independent data project and is not affiliated with or endorsed by {esc(name)}, the U.S. Department of Labor, USCIS, or the Department of State. Employer names appear as filed with DOL; figures are compiled from public disclosure data and may differ from an employer's own records.</p>
  </div>
</div>

""" + FOOTER + "\n" + ctx["widgets"] + "\n</body>\n</html>\n")
    return GENERATED_BANNER + "\n" + head + body


# ── hub page ─────────────────────────────────────────────────────────────────
def build_hub(members: List[dict], ctx: dict) -> str:
    total_emp = ctx["index"].get("totalEmployers")
    top_n = ctx["topN"]
    ranked = sorted([m for m in members if m.get("rank")], key=lambda m: m["rank"])
    top = [m for m in ranked if m["rank"] <= top_n][:top_n]
    sum_perm = sum(m.get("permSum", m.get("perm")) or 0 for m in top)
    dash = ctx["dash"]
    url = SITE + "/employers"
    title = f"Top {len(top)} PERM Green Card Sponsors: Employer Profiles ({today_et().year}) | ImmiLane"
    desc = (f"The {len(top)} U.S. employers with the most PERM (green card) labor certification filings in DOL data, with certification rates, "
            f"cases pending with DOL, job titles, wages and H-1B salaries for each. {n(sum_perm)} PERM cases across the top {len(top)}.")

    rows = []
    for m in top:
        h1b = m.get("h1b") or {}
        ps = perm_stats(h1b)
        ls = live_stats(m.get("live"))
        rows.append(f"<tr><td class=\"num\">{n(m['rank'])}</td><td class=\"txt\"><a href=\"/employers/{esc(m['slug'])}\">{esc(m['name'])}</a></td>"
                    f"<td class=\"num\">{n(ps['total'])}</td><td class=\"num\">{fmt_pct(ps['rate'])}</td>"
                    f"<td class=\"num\">{n(ls['pending']) if ls['tracked'] else '—'}</td><td class=\"num\">{usd(h1b.get('wage_median_all'))}</td></tr>")
    table = ('<div class="dt-wrap"><table class="dt" id="top-table"><thead><tr><th class="num">Rank</th><th>Employer</th><th class="num">PERM filings</th>'
             '<th class="num">Cert. rate</th><th class="num">Pending now</th><th class="num">Median H-1B salary</th></tr></thead>'
             f'<tbody>{"".join(rows)}</tbody></table></div>')

    # A–Z (every registry member, including any that slipped below the cut)
    def key_letter(name: str) -> str:
        s = re.sub(r"[^A-Za-z0-9]", "", name.upper())
        return s[0] if s and s[0].isalpha() else "#"
    groups: Dict[str, List[dict]] = {}
    for m in members:
        groups.setdefault(key_letter(m["name"]), []).append(m)
    letters = ["#"] + [chr(c) for c in range(65, 91)]
    az_nav = '<div class="az-nav">' + "".join((f'<a href="#az-{l if l != "#" else "num"}">{l}</a>' if l in groups else f"<span>{l}</span>") for l in letters) + "</div>"
    az_groups = ""
    for l in letters:
        if l not in groups:
            continue
        items = "".join(f'<li><a href="/employers/{esc(m["slug"])}">{esc(m["name"])}</a> <small>({n(m.get("permSum", m.get("perm")))})</small></li>'
                        for m in sorted(groups[l], key=lambda m: m["name"].lower()))
        az_groups += f'<div class="az-group" id="az-{l if l != "#" else "num"}"><h3>{l}</h3><ul>{items}</ul></div>'

    ld = [{"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [
              {"@type": "ListItem", "position": 1, "name": "ImmiLane", "item": SITE + "/"},
              {"@type": "ListItem", "position": 2, "name": "Employer PERM Profiles", "item": url}]},
          {"@context": "https://schema.org", "@type": "CollectionPage", "name": title, "url": url, "description": desc,
           "isPartOf": {"@type": "WebSite", "name": "ImmiLane", "url": SITE + "/"},
           "about": {"@type": "Dataset", "name": "PERM labor certification filings by employer",
                     "description": "U.S. Department of Labor OFLC PERM disclosure data, FY2008–FY2026, aggregated by employer.",
                     "url": url, "isAccessibleForFree": True, "creator": {"@type": "Organization", "name": "ImmiLane", "url": SITE + "/"}}}]
    ldtxt = "".join(f'<script type="application/ld+json">{json.dumps(o, ensure_ascii=False)}</script>\n' for o in ld)
    head = (HEAD_TOP + f"<title>{esc(title)}</title>\n<meta name=\"description\" content=\"{esc(desc)}\">\n<link rel=\"canonical\" href=\"{url}\">\n"
            f'<meta property="og:type" content="website">\n<meta property="og:title" content="{esc(title)}">\n<meta property="og:description" content="{esc(desc)}">\n'
            f'<meta property="og:url" content="{url}">\n<meta property="og:site_name" content="ImmiLane">\n<meta property="og:locale" content="en_US">\n'
            f'<meta name="twitter:card" content="summary">\n<meta name="twitter:title" content="{esc(title)}">\n<meta name="twitter:description" content="{esc(desc)}">\n' + ldtxt + HEAD_BOTTOM)
    body = (BODY_TOP + f"""
<div class="container">
  <div class="hero">
    <div class="eyebrow">Employers &middot; PERM green card sponsors</div>
    <h1>Top {len(top)} PERM Green Card Sponsors</h1>
    <p class="lede">The U.S. employers with the most PERM (green-card labor certification) filings in Department of Labor disclosure data, <b>FY2008–FY2026</b>. Together these {len(top)} companies account for <b>{n(sum_perm)}</b> PERM cases. Each profile shows filings by year, certification rate, cases currently pending with DOL (it is adjudicating <b>{esc(dash['frontier'])}</b> filings today), job titles, wages and H-1B salary data.</p>
  </div>
  <div class="breadcrumb"><a href="/">Dashboard</a> &rsaquo; Employer Profiles</div>

  <div class="content">
    <p>Ranked by total PERM cases in DOL's PERM disclosure files (certified, denied and withdrawn, FY2008–FY2026 year-to-date). "Pending now" is from ImmiLane's live case-status tracker (filings since November 2024); the H-1B salary is the median offered wage on {esc((top[0].get('h1b') or {}).get('fy') or 'FY2025') if top else 'FY2025'} LCA filings. Looking for a smaller employer? <a href="/leaderboard">Search all {n(total_emp)} employers</a>.</p>
{IN_CONTENT_AD}
    <h2 id="top">Top {len(top)} by PERM filing volume</h2>
    {table}

    <h2 id="az">All profiles A–Z</h2>
    {az_nav}
    {az_groups}

    <div class="cta-box"><p>Your employer's case is in the same DOL queue as everyone else's: see where DOL is today on the <a href="/">live dashboard</a>, read <a href="/guide-how-dol-processes-perm">how DOL processes PERM</a>, or get alerts with <a href="/subscribe">Case Watch</a>.</p></div>
    <p class="sources">Sources: U.S. Department of Labor OFLC PERM (ETA-9089) and LCA (ETA-9035) disclosure files; ImmiLane live PERM case-status tracker. Page updated {esc(ctx['generated'])}.</p>
    <p class="disclaimer">Informational only &mdash; not legal advice. ImmiLane is an independent data project and is not affiliated with or endorsed by any employer listed here, the U.S. Department of Labor, USCIS, or the Department of State.</p>
  </div>
</div>

""" + FOOTER + "\n" + ctx["widgets"] + "\n</body>\n</html>\n")
    return GENERATED_BANNER + "\n" + head + body


# ── sitemap + employer.html blocks ───────────────────────────────────────────
def sitemap_block(members: List[dict], hub_lastmod: str) -> str:
    out = [f"\n  <url>\n    <loc>{SITE}/employers</loc>\n    <lastmod>{hub_lastmod}</lastmod>\n    <changefreq>daily</changefreq>\n    <priority>0.8</priority>\n  </url>"]
    for m in sorted(members, key=lambda m: (m.get("rank") or 10**9, m["slug"])):
        out.append(f"\n  <url>\n    <loc>{SITE}/employers/{m['slug']}</loc>\n    <lastmod>{m.get('lastmod') or hub_lastmod}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>0.6</priority>\n  </url>")
    return "".join(out) + "\n  "


def employer_html_block(members: List[dict]) -> str:
    """JSON map of {canonical h1b slug | name slug: static slug} for employer.html."""
    mp: Dict[str, str] = {}
    for m in members:
        for k in (m.get("h1bSlug"), normalize_slug(m["name"]), m.get("liveSlug")):
            if k:
                mp[k] = m["slug"]
    return '\n<script id="il-static-employers" type="application/json">' + json.dumps(mp, sort_keys=True, separators=(",", ":")) + "</script>\n"


# ── orchestration ────────────────────────────────────────────────────────────
def dashboard_ctx(root: str) -> dict:
    D = load_json(os.path.join(root, DASH_REL))
    dol = D["dol"]
    mm = re.search(r"'(\d\d)", dol.get("label", ""))
    yr = ("20" + mm.group(1)) if mm else ""
    return {"frontier": dol["monthFull"] + (f" {yr}" if yr else ""), "pct": f"{dol['pctProcessed']}%",
            "remain": n(dol["casesRemaining"]), "avg": str(D["avgDays"]["current"]), "avgCert": str(D["avgDays"]["certified"]),
            "pending": n(D["backlog"]["total"]), "updated": fmt_et_long(D["updatedAt"])}


def render_all(root: str, reg: dict, check: bool = False) -> List[str]:
    members = reg["employers"]
    top_n = (reg.get("selection") or {}).get("top") or DEFAULT_TOP
    # lastmod: today when the page's data changed vs the committed snapshot, else keep
    today = today_et().isoformat()
    extras_all = load_json(os.path.join(root, EXTRAS_REL)) or {}
    for m in members:
        fp = fingerprint(m, (extras_all.get("employers") or {}).get(m["slug"]))
        if m.get("fingerprint") != fp or not m.get("lastmod"):
            m["fingerprint"], m["lastmod"] = fp, today
    for m in members:  # the figure every page/hub row shows (same source as the interactive profile)
        m["permSum"] = perm_stats(m.get("h1b") or {})["total"]
    ranked = sorted([m for m in members if m.get("rank")], key=lambda m: m["rank"])
    related: Dict[str, List[dict]] = {}
    for i, m in enumerate(ranked):
        neigh = [ranked[j] for j in range(max(0, i - 3), min(len(ranked), i + 4)) if j != i]
        related[m["slug"]] = neigh[:6]
    # "Page updated" is stamped to the day (not the minute) so re-rendering the same
    # data is a byte-for-byte no-op — no spurious file churn on every deploy.
    ctx = {"dash": dashboard_ctx(root), "index": reg.get("index") or {}, "liveMeta": reg.get("liveMeta") or {},
           "extras": extras_all, "related": related, "topN": top_n,
           "widgets": shared_widgets(root), "generated": today_et().strftime("%b %-d, %Y")}
    outputs: Dict[str, str] = {}
    for m in members:
        outputs[os.path.join(OUT_DIR, m["slug"] + ".html")] = build_page(m, ctx)
    outputs[HUB_REL] = build_hub(members, ctx)
    # sitemap + employer.html blocks
    sm_path = os.path.join(root, "sitemap.xml")
    sm = open(sm_path, encoding="utf-8").read()
    if "<!--il-ssr:employers-->" not in sm:
        sm = sm.replace("</urlset>", "  <!--il-ssr:employers--><!--/il-ssr:employers-->\n</urlset>")
    hub_lastmod = max([m["lastmod"] for m in members] + [today])
    outputs["sitemap.xml"] = sub_marked(sm, "employers", sitemap_block(members, hub_lastmod))
    eh_path = os.path.join(root, "employer.html")
    eh = open(eh_path, encoding="utf-8").read()
    if "<!--il-ssr:static-employers-->" in eh:
        outputs["employer.html"] = sub_marked(eh, "static-employers", employer_html_block(members))
    changed = []
    for rel, content in outputs.items():
        p = os.path.join(root, rel)
        old = open(p, encoding="utf-8").read() if os.path.exists(p) else None
        if old != content:
            changed.append(rel)
            if not check:
                os.makedirs(os.path.dirname(p) or ".", exist_ok=True)
                tmp = p + ".render.tmp"
                with open(tmp, "w", encoding="utf-8") as f:
                    f.write(content)
                os.replace(tmp, p)
    return changed


def deploy_step(root: str, check: bool = False) -> str:
    """Called by render_live.py at deploy time: refresh from the worker (per-employer
    fallback to the committed snapshot) and re-render. Returns a one-line summary."""
    reg_path = os.path.join(root, REGISTRY_REL)
    reg = load_json(reg_path)
    if not reg or not reg.get("employers"):
        return "employer pages: no registry — skipped"
    apply_index(root, reg)
    reg = refresh(reg)
    changed = render_all(root, reg, check=check)
    if not check:
        save_json(reg_path, reg)
    rs = reg.get("refreshStats") or {}
    pages = sum(1 for c in changed if c.startswith(OUT_DIR + "/"))
    return (f"employer pages: {len(reg['employers'])} members · worker ok {rs.get('h1bOk')}/{rs.get('members')} "
            f"({rs.get('errors')} with fetch errors → snapshot fallback) · {'would change' if check else 'rendered'} {pages} page(s) + {len(changed) - pages} other file(s)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    ap.add_argument("--select", action="store_true")
    ap.add_argument("--refresh", action="store_true")
    ap.add_argument("--render", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--probe-all", action="store_true", help="re-probe every live-tracker slug candidate")
    ap.add_argument("--top", type=int, default=DEFAULT_TOP)
    a = ap.parse_args()
    root = a.root
    reg_path = os.path.join(root, REGISTRY_REL)
    reg = load_json(reg_path, {"version": 1, "employers": []})
    if a.select:
        reg, added = select_members(root, reg, a.top)
        print(f"select: {len(reg['employers'])} members ({len(added)} added)")
    apply_index(root, reg)
    if a.refresh:
        reg = refresh(reg, probe_all=a.probe_all or a.select)
        rs = reg["refreshStats"]
        print(f"refresh: h1b ok {rs['h1bOk']}/{rs['members']}, {rs['errors']} with errors; live entries {sum(1 for m in reg['employers'] if m.get('live'))}")
    if a.render:
        changed = render_all(root, reg, check=a.check)
        print(f"render: {'would change' if a.check else 'wrote'} {len(changed)} file(s)")
    if not a.check and (a.select or a.refresh or a.render):
        save_json(reg_path, reg)
        print(f"saved {REGISTRY_REL}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
